### PR TITLE
Fix: traefik mount with rw / ro

### PR DESCRIPTION
**Pull request by anbraten**
I added a more robust regex so if your exoframe-server mount looks like: `/home/anbraten/exoframe-server/data:/root/.exoframe:rw` it would match, so `traefikPath` would be the remaining string after removing `:/root/.exoframe:rw`. 

PS: `:rw` was added, because I tried running the server with docker-compose.

### CODE REVIEW

**Comment by yamalight** [comment]
Seems great, thank you!
One small request - could you please add a test that validates this works as expected?

(note: travis currently fails because it can't reach docker hub, this happens randomly for some reason)

**Comment by anbraten** [comment]
> One small request - could you please add a test that validates this works as expected?
Sure. Currently there is no test for the traefik setup at all, correct? Seems like all current test are for fastify endpoints / routes folder?

**Comment by yamalight** [comment]
@anbraten there is a test that lives in [`update.test.js`](https://github.com/exoframejs/exoframe-server/blob/master/test/update.test.js#L91)
A bit weird placing, but there was no need to test traefik outside of updating till now 😅

**Comment by yamalight** [comment]
This is some great stuff! Feel a bit like an idiot looking at your code 😅 
Merging. Thanks for your work!

**Pull request merged**
