### PR TITLE
Updated docker labels. Fixes exoframejs/exoframe/issues/151

### PR DESCRIPTION
**Pull request by JoyceBabu**
Add `traefik.docker.network` and `traefik.enable` labels to created docker containers

### CODE REVIEW

**Comment by yamalight** [comment]
@JoyceBabu could you please also add checks for the labels to deployment tests?

**Comment by yamalight** [comment]
@JoyceBabu `traefik.enable` label seems to be [missing](https://travis-ci.org/exoframejs/exoframe-server/builds/390383087#L522) for deployments 🤔  could you please have a look?

**Comment by JoyceBabu** [comment]
Yes, I noticed the build output. I was unable to run the tests locally due to some docker issues. I will try debugging it later.

**Comment by yamalight** [comment]
Great, thanks! I'll see if I can find some time to figure out what's wrong as well 🤔

**Comment by JoyceBabu** [comment]
I have fixed the test errors by adding `traefik.enable` to `exoframe-server/src/docker/templates/compose.js`.

**Comment by yamalight** [comment]
yep, looks good. thanks!

**Pull request merged**
