### PR TITLE
[WIP] Add support for private Docker repositories / registries

### PR DESCRIPTION
**Pull request by maxime1992**
This closes exoframejs/exoframe#117

### CODE REVIEW

**Comment by maxime1992** [comment]
Hey @yamalight :smiley_cat: 

I've decided to try fixing exoframejs/exoframe#117 but as I don't have much time to work on that I'd really appreciate a bit of help from you, to help me understand how things work around.

I've noticed that you're using `dockerode` and I read the documentation.
I found that it's possible to connect to private registries by setting the auth.
I tried with a small dockerode project to pull my private Docker image and it did work.

So my question is, how can that be useful?
If I have a Docker-compose file where let say I define my private image. Docker will try by itself to pull it, am I correct? So This approach would only work for non docker-compose project? For one Docker image only? Can you think of a better approach?

**Comment by yamalight** [comment]
@maxime1992 this is awesome! thank you for your work ❤️ 

Yes indeed, this would only work for non-compose deployments. Compose is kinda completely separate from the rest of exoframe. I think `docker stack` has `--with-registry-auth` flag for that, but I'm not sure just compose can be addressed 🤔 
Might be simpler to just document that you have to log in with your docker daemon manually (since compose is executed via binary invocation).

**Comment by yamalight** [comment]
@maxime1992 I'd absolutely love to have that for normal docker deployments.
I'd say the config should be read from two places:
1) globally from exoframe-server config
2) locally from project config
If local exists - it's the one that's used, if not - fall back to global, if it doesn't exists - don't attach anything 🤔 

Small note: please change the PR target to `develop` branch 😃

**Comment by maxime1992** [comment]
Sorry I completely lost track on that one and would probably be faster to rework from group up.

Feel free to reopen or take over!

**Comment by alexanderadam** [comment]
Oh no! :crying_cat_face:

**Pull request closed without merging**
