### PR TITLE
Add authentication for docker-compose and normal docker build commands

### PR DESCRIPTION
**Pull request by Aeolun**
There was already a pull request for this, but it was half finished (and inactive?), and to fully make use of Exoframe I really need this functionality, so I made a different one.

Please let me know what you think.

### CODE REVIEW

**Comment by yamalight** [comment]
From a quick glance - this is awesome!
I'll review the code once I have time.
Thanks!

**Comment by yamalight** [comment]
@Aeolun quick first request - please add tests for all the new functionality.

**Comment by Aeolun** [comment]
@yamalight Sure. Two questions though, Travis currently fails, but it doesn't appear to be because the tests don't succeed. Should I change any setting, or is this expected (since it cannot log into docker hub, which I guess it only does for the main branch?)

Lastly, is there any way to easily run the whole testsuite locally without polluting my docker environment with the test images? Basically, the first run goes ok, but after that it fails because all test images are already there.

**Comment by yamalight** [comment]
@Aeolun it might be because of that docker hub breach and password resets that happened recently, I'll check the bot password once I have time - as long as the tests pass, you should be good :)

W.r.t. images - you have to do a manual cleanup after test(s) if you want those images to be gone on subsequent runs.

**Comment by yamalight** [comment]
Closing this as stale. Feel free to re-open if needed.

**Pull request closed without merging**
