### PR TITLE
WIP: Add custom traefik labels

### PR DESCRIPTION
**Pull request by anbraten**
Adds way to set custom traefik container labels

Fixes: exoframejs/exoframe#147

### CODE REVIEW

**Comment by yamalight** [comment]
@anbraten why would you need that if you can customize config? 🤔

**Comment by anbraten** [comment]
@yamalight To enable api and dashboard (exoframejs/exoframe#147)

**Comment by yamalight** [comment]
@anbraten you can do that via config, right? 🤔

**Comment by anbraten** [comment]
Don't think so. You have to enable it in the static configuration:
```
api:
  dashboard: true
```

And add labels to the traefik container for the dynamic configuration like:
```
      - "traefik.enable=true"
      - "traefik.docker.network=exoframe"
      - "traefik.http.middlewares.${name}-https.redirectscheme.scheme=https"
      - "traefik.http.routers.${name}.tls.certresolver=exoframeChallenge"
      - "traefik.http.routers.${name}.entrypoints=websecure"
      - "traefik.http.routers.${name}.service=api@internal"
      - "traefik.http.routers.${name}.rule=Host('traefik.example.org')"
      - "traefik.http.routers.${name}.middlewares=${MIDDLEWARES}"
      - "traefik.http.middlewares.traefikauth.basicauth.users=admin:hashedpassword"
```

https://docs.traefik.io/v2.0/operations/dashboard/#dashboard-router-rule

**Comment by yamalight** [comment]
Aha, didn't know it only worked with static config. Then this makes perfect sense 👍

**Comment by yamalight** [comment]
This PR seems to combine #31 with custom labels - am I right? 🤔

**Comment by anbraten** [comment]
> This PR seems to combine #31 with custom labels - am I right? thinking

Ohh, sorry. 🙈
I will redo this PR based on the current develop branch instead.

**Pull request closed without merging**
